import React, { useState } from "react";
import axios from "axios";
import JSZip from "jszip";
import { saveAs } from "file-saver";

function App() {
  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [files, setFiles] = useState(null);
  const [error, setError] = useState(null);

  const generateExtension = async () => {
    if (!prompt) return alert("Please enter a prompt!");
    setLoading(true);
    setError(null);
    setFiles(null);

    try {
      // ⚠️ CHANGE THIS to your actual Render URL
      const response = await axios.post("https://extension-generator-backend-p4m9.onrender.com/generate", { 
        prompt 
      });

      if (response.data && response.data.message) {
        setFiles(response.data.message);
      } else {
        throw new Error("Invalid response from AI");
      }
    } catch (err) {
      console.error("Frontend Error:", err);
      setError(err.response?.data?.details || err.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadZip = () => {
    if (!files) return;

    const zip = new JSZip();

    try {
      let manifestObj = files["manifest.json"];
      
      // Safety check: Convert string manifest to object if needed
      if (typeof manifestObj === "string") {
        manifestObj = JSON.parse(manifestObj);
      }

      // Ensure manifest_version is exactly 3 (Integer)
      manifestObj.manifest_version = 3;

      zip.file("manifest.json", JSON.stringify(manifestObj, null, 2));
      zip.file("content.js", files["content.js"] || "");
      zip.file("popup.html", files["popup.html"] || "<html><body><h3>Generated by Xtensio</h3></body></html>");

      zip.generateAsync({ type: "blob" }).then((content) => {
        saveAs(content, "extension.zip");
      });
    } catch (err) {
      alert("Error building ZIP: " + err.message);
    }
  };

  return (
    <div style={{ padding: "40px", textAlign: "center", fontFamily: 'Segoe UI', backgroundColor: '#f0f2f5', minHeight: '100vh' }}>
      <div style={{ backgroundColor: 'white', padding: '30px', borderRadius: '15px', display: 'inline-block', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}>
        <h1>🚀 Xtensio AI</h1>
        <p>Generate Chrome Extensions in seconds</p>
        
        <textarea
          placeholder="What should the extension do? (e.g. Change background to blue)"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          style={{ width: "400px", height: "120px", padding: "15px", borderRadius: "10px", border: '1px solid #ddd' }}
        />
        <br />
        
        <button 
          onClick={generateExtension} 
          disabled={loading}
          style={{ 
            marginTop: "20px", padding: "12px 30px", fontSize: "16px", 
            backgroundColor: "#007bff", color: "white", border: "none", 
            borderRadius: "5px", cursor: "pointer" 
          }}
        >
          {loading ? "Magic in progress..." : "Generate Extension"}
        </button>

        {error && <p style={{ color: "red", marginTop: "20px" }}>❌ {error}</p>}

        {files && (
          <div style={{ marginTop: "30px", borderTop: '1px solid #eee', paddingTop: '20px' }}>
            <h3 style={{ color: '#28a745' }}>✅ Generation Complete!</h3>
            <button 
              onClick={downloadZip}
              style={{ padding: "12px 25px", backgroundColor: "#28a745", color: "white", border: "none", borderRadius: "5px", cursor: "pointer", fontWeight: 'bold' }}
            >
              📥 Download .ZIP File
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default App;